apiVersion: apps/v1
kind: Deployment
metadata:
  name: gold-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gold
  template:
    metadata:
      labels:
        app: gold
    spec:
      containers:
        - name: gold
          image: 176646220910.dkr.ecr.us-east-1.amazonaws.com/shopping-site-gold:9c74bdfa20e937dc88a600f75c21e427f979eb3f
          ports:
            - containerPort: 80
