apiVersion: apps/v1
kind: Deployment
metadata:
  name: pearl-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pearl
  template:
    metadata:
      labels:
        app: pearl
    spec:
      containers:
        - name: pearl
          image: 176646220910.dkr.ecr.us-east-1.amazonaws.com/shopping-site-pearl:9c74bdfa20e937dc88a600f75c21e427f979eb3f
          ports:
            - containerPort: 80
